variables:
  - group: "WebTMA7 Functional Tests"

trigger: none

schedules:
  - cron: 0 12 * * *
    branches:
      include:
        - refs/heads/main
jobs:
  - job: Job_1
    displayName: Functional Tests Nightly - Smoke
    timeoutInMinutes: 90
    condition: succeededOrFailed()
    strategy:
      parallel: 4

    pool:
      vmImage: ubuntu-latest

    steps:
      - task: UseNode@1
        displayName: use node
        inputs:
          version: 19.x
          checkLatest: true

      - script: npm ci
        displayName: "Install NPM dependencies"

      - script: npx cypress verify
        displayName: "Cypress verify"

      - script: npx cypress info
        displayName: "Cypress info"

      - script: >
          CYPRESS_BASE_URL=https://sandbox.webtma.com 
          npx cypress run 
          -e grepTags=@smoke,user1='{"loginId":"qat","password":"qat","clientName":"sandbox"}',userRequestor='{"loginId":"katreq","password":"katrina","clientName":"sandbox"}' 
          -b chrome 
          -r junit 
          -o mochaFile=generated/reports/junit/report.xml 
          --record 
          -t "nightly,dc05,smoke" 
          --parallel 
          --ci-build-id $BUILD_BUILDNUMBER
        displayName: "Run Cypress tests"
        env:
          # avoid warnings about terminal
          TERM: xterm
          # map the secret Cypress record key as environmental variable for this step
          CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)

      - task: PublishTestResults@2
        displayName: show test results
        condition: succeededOrFailed()
        continueOnError: True
        inputs:
          testResultsFiles: generated/reports/junit/*.xml
          mergeTestResults: true
